return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    spec = {
      { "<leader>t", group = "翻訳", icon = "󰗊" },
      { "<leader>tr", mode = "v", desc = "選択範囲の翻訳", icon = "󰗊" },
      { "<leader>tw", desc = "単語の翻訳", icon = "󰗊" },
      { "<leader>f", group = "検索", icon = "󰱼" },
      { "<leader>ff", desc = "ファイル検索", icon = "󰱼" },
      { "<leader>fg", desc = "文字列検索", icon = "󰱼" },
      { "<leader>fb", desc = "バッファ一覧", icon = "󰱼" },
      { "<leader>fh", desc = "ヘルプ検索", icon = "󰱼" },
      { "<leader>fr", desc = "最近開いたファイル", icon = "󰱼" },
      { "<leader>fc", desc = "コマンド一覧", icon = "󰱼" },
      { "<leader>g", group = "Git", icon = "" },
      { "<leader>gm", desc = "コミット詳細の表示", icon = "" },
      { "<leader>l", group = "Lazy", icon = "󰒲" },
      { "<leader>ld", desc = "LazyDocker", icon = "󰒲" },
      { "<leader>lg", desc = "LazyGit", icon = "󰒲" },
      { "<leader>e", desc = "ファイルツリー表示/非表示", icon = "" },
      { "<leader>w", desc = "バッファを閉じる", icon = "󰅙" },
      { "<leader>z", group = "禅", icon = "󰑮" },
      { "<leader>zm", desc = "禅モード", icon = "󰑮" },
      { "<leader>x", group = "診断", icon = "󰋼" },
      { "<leader>xx", desc = "診断一覧", icon = "󰋼" },
      { "<leader>xX", desc = "バッファの診断", icon = "󰋼" },
      { "<leader>xL", desc = "エラー箇所リスト", icon = "󰍜" },
      { "<leader>xQ", desc = "修正候補リスト", icon = "󰁨" },
      { "<leader>c", group = "コード", icon = "" },
      { "<leader>cs", desc = "関数/クラス一覧", icon = "󰫧" },
      { "<leader>cl", desc = "LSP 定義/参照", icon = "󰡦" },
      { "gc", group = "コメント", icon = "󰅺" },
      { "gcc", desc = "行コメントのトグル", icon = "󰅺" },
      { "gc", mode = "v", desc = "選択範囲の行コメントのトグル", icon = "󰅺" },
      { "<leader>s", hidden = true },
    },
  },
}
